
import javax.swing.JOptionPane;
import project.InsertUpdateDelete;
//import sun.misc.Signal;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ELCOT
 */
public class signup extends javax.swing.JFrame {

   // private Object Cars;

   

    /**
     * Creates new form sinup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tx_id = new javax.swing.JTextField();
        Tx_Email = new javax.swing.JTextField();
        Tx_mobileNumber = new javax.swing.JTextField();
        pw_password = new javax.swing.JPasswordField();
        But_reser = new javax.swing.JButton();
        but_Login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Tx_name = new javax.swing.JTextField();
        but_signup = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("  Register");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("userid");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("MobileNumber");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password");

        Tx_id.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Tx_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tx_idActionPerformed(evt);
            }
        });
        Tx_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tx_idKeyReleased(evt);
            }
        });

        Tx_Email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Tx_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tx_EmailActionPerformed(evt);
            }
        });
        Tx_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tx_EmailKeyReleased(evt);
            }
        });

        Tx_mobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Tx_mobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tx_mobileNumberKeyReleased(evt);
            }
        });

        pw_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_passwordActionPerformed(evt);
            }
        });
        pw_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pw_passwordKeyReleased(evt);
            }
        });

        But_reser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        But_reser.setText("RESET");
        But_reser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_reserActionPerformed(evt);
            }
        });

        but_Login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        but_Login.setText("Login");
        but_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_LoginActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Name");

        Tx_name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Tx_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tx_nameActionPerformed(evt);
            }
        });
        Tx_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tx_nameKeyReleased(evt);
            }
        });

        but_signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        but_signup.setText("signup");
        but_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_signupActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(but_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(but_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(But_reser, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(397, 397, 397))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Tx_mobileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                .addComponent(pw_password)
                                .addComponent(Tx_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tx_id, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Tx_name, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(377, 377, 377))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(412, 708, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 378, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tx_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tx_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tx_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tx_mobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pw_password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(But_reser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 55, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 696, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tx_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tx_idKeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_Tx_idKeyReleased

    private void Tx_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tx_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tx_EmailActionPerformed

    private void Tx_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tx_EmailKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_Tx_EmailKeyReleased

    private void Tx_mobileNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tx_mobileNumberKeyReleased
        // TODO add your handling code here:
       

    }//GEN-LAST:event_Tx_mobileNumberKeyReleased

    private void pw_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw_passwordActionPerformed

    private void pw_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw_passwordKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_pw_passwordKeyReleased

    private void But_reserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_reserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_But_reserActionPerformed

    private void but_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_LoginActionPerformed

    private void Tx_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tx_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tx_nameActionPerformed

    private void Tx_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tx_nameKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Tx_nameKeyReleased

    private void but_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_signupActionPerformed
        // TODO add your handling code here:
          String name=Tx_name.getText();
          String id =Tx_id.getText();
          String Email =Tx_Email.getText();
          String mobileNumber=Tx_mobileNumber.getText();
          String password =pw_password.getText();
          // name VARCHAR(200),id int(100)  primary key, Email  VARCHAR(100),mobileNumber int(100),password  VARCHAR(100))
          //String confirmpassword =Pw_ConfirmPassword.getText();
        if(name.equals("") ||id.equals("") || Email.equals("")||mobileNumber .equals("")||password.equals(""))
            JOptionPane.showMessageDialog(null,"Every field is Required");
        else
        { //+name+"','"+id+"','"+Email+"','"+mobileNumber+"','"+password+
            String Query;
            Query="insert into  Cars VALUES('"+name+"','"+id+"','"+Email+"','"+mobileNumber+"','"+password+"')";
            InsertUpdateDelete.setData(Query,"Registered Successfully");
        
            setVisible(false);
            new login().setVisible(true);
        }
  
    }//GEN-LAST:event_but_signupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          int  a=JOptionPane.showConfirmDialog(null,"DO YOU REALLY WANT TO CLOSE APPLICATION","SELECT",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Tx_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tx_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tx_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton But_reser;
    private javax.swing.JTextField Tx_Email;
    private javax.swing.JTextField Tx_id;
    private javax.swing.JTextField Tx_mobileNumber;
    private javax.swing.JTextField Tx_name;
    private javax.swing.JButton but_Login;
    private javax.swing.JButton but_signup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pw_password;
    // End of variables declaration//GEN-END:variables
}
